name: NuGet Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Build Mod
      # This command will automatically download MonoGame 3.8.1
      run: dotnet build --configuration Release

    - name: Save Artifact
      uses: actions/upload-artifact@v4
      with:
        name: LeftyMode-Output
        path: bin/Release/net6.0/
        
